


Server:
  host: "localhost"
  port: 8080
  context-path: "api/"

Person:
  firstName: "John"
  lastName: "Doe"
  Page: ${random.int(20,50)}
  id: ${random.uuid}
  phone: 1234567890

student:
  name: 张小飞
  age: 20
  happy: true
  birth: 2004/01/01
  map:  {k1: v1, k2: v2}
  list:
    - code
    - read
    - music
  dog:
    name: 虎子
    age: 11





db:
  url: jdbc:mysql://127.0.0.1:3306/spring-boot?userUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
  username: root
  password: 123456
  driver-class-name: com.mysql.cj.jdbc.Driver


jwt:
  secret: helloworld
  expiration: 3600000  # 1小时 单位：ms

custom:
  qrcode:
    content: "http//www.baidu.com"
  log:
    level: "INFO"
  backup:
    location: /C:/Users/18361/Desktop/log/backup.log

spring:
  mail:
    host: smtp.qq.com
    username: 2124015394@qq.com
    password: pnsnbkysznhhcaba
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


  web:
    resources:
      static-locations: classpath:/static/,file:${file.upload-path}
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 10485760